### ISSUE TITLE
'animation: true' has an annoying effect during render

### ISSUE THREAD

**Issue by Jonsonmon** [MelleD/lovelace-expander-card#722]
The animations look great, and big thanks to @dcapslock!

There’s an issue with the transition, as it also appears when the card is first rendered. `(transition: background-color)`
It results in inconsistency between the cards on the dashboard and looks a bit odd

**Comment by dcapslock** [comment]
@Jonsonmon (@MelleD FYI). I have been thinking about this, and it would be plausible to make the animation duration a CSS var and set at 0/1ms until the after first update. This would also mean any cards that are `expanded: true` would not expand with animation.

The other option is to remove the background-color transition. As you were the one who asked for it, I suppose you get to chose what you best suits your need. I am of the view that it is fine as implemented. If you can style your card background higher up for the card with card-mod (v4 can style sections so you can set --card-background-color for cards in a section), for example, you would likely not see the animation flash as the background of the card would be your desired initial color.

**Comment by Jonsonmon** [comment]
I think that when `expanded: true`, there shouldn’t be any animation at all - it should rendered expanded.
I’m fine with adding this delay, it gives a cleaner and more consistent look across dashboard
Your decision @MelleD @dcapslock  :)

**Comment by dcapslock** [comment]
I am in two minds. I actually like seeing the animation of cards expanded by default. I am for the option of leaving as is.

**Comment by MelleD** [comment]
As I mentioned in the discussion, the background switching doesn't bother me, and it works for me.

I've noticed this with a few other cards as well. As long as everything works smoothly after the initial load, I'm happy. I don't even look at my dashboard until it's loaded anyway :-).

Maybe I can make video that this also happens with other cards. Also if you a higher loading time when you have a lot of cards  I think it's okay.

**Comment by dcapslock** [comment]
I don't think we should change the opening animation at all. I am sure there are users already used to it with `expanded: true`, and if it bothered them they would have posted an issue. `animation: true` is that. You get animation. You don't want it then `animation: false`. Easy as that.

@Jonsonmon can I ask what your theme is for card background? if it is not the same as the background you have for collapsed, why not? I am of the belief that if your card background is the same as collpased colour you won't have any issue. If not then with `animation: true` you get animation from card color to collapsed background colour.

**Comment by MelleD** [comment]
Maybe here an example from my dashboard. It takes up to 1 second to load, because of the coloring and expanding type and icons loading.

Firs state:

<img width="325" height="483" alt="Image" src="https://github.com/user-attachments/assets/4b6e910e-e03a-49bc-9ecf-d2894ac63905" />

Wait Wait...

<img width="324" height="634" alt="Image" src="https://github.com/user-attachments/assets/8c7d1b8f-99a3-48d5-adef-393413fc82f6" />

Finish render (0,1 - 1 second)

<img width="321" height="705" alt="Image" src="https://github.com/user-attachments/assets/9a39f022-6c0d-4370-a3bc-256da83aad99" />

**Comment by dcapslock** [comment]
@Jonsonmon fixed by PR #755

**Comment by Jonsonmon** [comment]
> [@Jonsonmon](https://github.com/Jonsonmon) fixed by PR [#755](https://github.com/MelleD/lovelace-expander-card/pull/755)

Thanks 👍👍

**Comment by Jonsonmon** [comment]
Now I noticed that with `animation: false` this bug is still exist @dcapslock 
Can you reproduce?

**Comment by dcapslock** [comment]
Please open a new issue.

**Comment by Jonsonmon** [comment]
@dcapslock Thanks
#783
